import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles((theme) => ({
  mainContainer: {
    padding: "0px",
    margin: "0px",
    width: "100%",
    overflow: "hidden !important",
  },
  container: {
    display: "flex",
    minWidth: "100%",
    position: "relative",
    transform: (props) => "translateX(" + parseInt(props.slideIndex) + "vw)",
    transition: "all 1.5s ease",
  },
  sliderContainer: {
    overflow: 'hidden !important',
    height: props => props.type === "home" ? "100vh" : "70vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  content: {
    marginLeft: "200px",
    width: "30%",
  },
  slogan: {
    color: "#a4c639",
    fontSize: "22px",
    fontWeight: 700,
    letterSpacing: "1px",
    lineHeight: "26.4px",
    textTransform: "uppercase",
  },
  title: {
    color: "#ffffff",
    fontSize: "44px",
    fontWeight: 700,
    letterSpacing: "2.5px",
    lineHeight: "52.8px",
    textTransform: "uppercase",
    margin: "15px 0px 30px 0px",
  },
  desc: {
    color: "#ffffff",
    fontSize: "15px",
    lineHeight: "30px",
    marginBottom: "40px",
  },
  link: {
    backgroundColor: "#a4c639",
    borderRadius: "30px",
    padding: "12px 30px",
    color: "#ffffff",
    lineHeight: "19.5px",
    textTransform: "uppercase",
    textDecoration: "none",
    fontSize: "13px",
    fontWeight: 700,
  },
  leftArrow: {
    position: "absolute",
    left: "10px",
    top: "50%",
    width: "50px",
    height: "50px",
    cursor: "pointer",
    opacity: 0.5,
    zIndex: 999,
    backgroundColor: "#D5D5D5",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 1s ease",
    "&:hover": {
      transform: "scale(1.3)",
    },
  },
  rightArrow: {
    position: "absolute",
    right: "10px",
    top: "50%",
    width: "50px",
    height: "50px",
    cursor: "pointer",
    opacity: 0.5,
    zIndex: 2,
    backgroundColor: "#D5D5D5",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 1s ease",
    "&:hover": {
      transform: "scale(1.3)",
    },
  },
  titleOther:{
    color: '#ffffff',
    fontSize: '36px',
    fontWeight: 700,
    letterSpacing: 2,
    lineHeight: "43.22px",
    marginBottom: '18px',
    textAlign: 'center',
  },
  descOther:{
    color: '#ffffff',
    fontSize: '15px',
    letterSpacing: '1px',
    lineHeight: "30.5px",
    textAlign: 'center',
    padding: '0px 205px',
    textTransform: 'uppercase',
  }
}));
