import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles((theme) => ({
  container: {
    position: (props) => (props.isScrolled ? "fixed" : "absolute"),
    backgroundColor: (props) => (props.isScrolled ? "#ffffff" : ""),
    top: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
    height: "71px",
    zIndex: 999,
    margin: 0,
    padding: 0,
    overflow: "hidden !important",
  },
  left: {
    fontSize: "24px",
    fontWeight: "700px",
    lineHeight: "28px",
    textTransform: "uppercase",
    color: "#a4c639",
  },
  right: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
  },
  menu: {
    marginRight: "30px",
    textDecoration: "none",
    fontSize: "15px",
    fontWeight: "200",
    letterSpacing: "0.5px",
    textTransform: "capitalize",
    padding: "10px",
    color: (props) => (props.isScrolled ? "#1e1e1e" : "#ffffff"),
    cursor: "pointer",
  },
  Account: {
    marginRight: "30px",
    textDecoration: "none",
    fontSize: "15px",
    fontWeight: "200",
    letterSpacing: "0.5px",
    textTransform: "capitalize",
    padding: "10px",
    color: (props) => (props.isScrolled ? "#1e1e1e" : "#ffffff"),
    cursor: "pointer",
  },
  menuUl: {
    listStyle: "none",
    position: "fixed",
    right: "200px",
    top: "71px",
    zIndex: 999,
    backgroundColor: (props) => (props.isScrolled ? "#ffffff" : ""),
    borderRadius: "0px 0px 10px 10px",
    textAlign: "center",
    visibility: (props) => (props.open ? "visible" : "hidden"),
    opacity: (props) => (props.open ? 1 : 0),
    transition: "all 0.5s ease",
    color: (props) => (props.isScrolled ? "black" : "white"),
  },
  menuItem: {
    padding: "10px 20px",
    fontSize: "14px",
    lineHeight: "25px",
    cursor: "pointer",
    width: "100%",
    "&:hover": {
      backgroundColor: "lightgrey",
      borderRadius: "10px",
      color: "red",
      width: "100%",
      opacity: 0.5,
    },
  },
  menuActive: {
    color: "#a4c639 !important",
    lineHeight: "22.5px",
    borderBottom: "1px solid #a4c639 !important",
    display: "block",
  }
}));
